### ISSUE TITLE
Get Doom PoC up and running

### ISSUE THREAD

**Issue by icedream** [icedream/denon-prime4#17]
See #9.

So far fighting with graphics driver/rendering since it does not want to recognize the GPU chip or something.

**Comment by erhan-** [comment]
I got it running and retroarch with opengl as well. Both with audio and controlling over the buttons and jog wheel. Two player is also possible, I will make another video on it later with a friend:

https://www.instagram.com/p/DZxjS0WoUe5/

I will upload all code soon, its a bit messy organized. Just wanted to let you know because we wanted this for years literally.

**Comment by icedream** [comment]
@erhan- That's crazy!! Glad to see someone else made it work all the way :D

**Comment by erhan-** [comment]
Here is the doom port https://github.com/erhan-/doomgo

Here is a launcher: https://github.com/erhan-/primelauncher

Here is retroarch and a SNES, PSX and GB core:  https://github.com/erhan-/retrogo
