### ISSUE TITLE
Risk of permanently bricking my device? Can I add music over SSH?

### ISSUE THREAD

**Issue by iikkart** [icedream/denon-prime4#49]
Hi! I have a couple of beginner questions:

1) Is there a risk that I can brick my device if I follow these instructions? How could I recover my device if something goes wrong? Also if any other reason I want to go back to stock firmware, what's the flow for that? 

2) Could I move music from my computer over SSH to my device's SSD after rooting? 

I would greatly appreciate your answer. Thanks for you hard work to reverse engineer this beautiful device! <3

**Comment by icedream** [comment]
Hey @iikkart, sorry for the late reply.

The only thing the firmware currently is supposed to do is add binaries and configuration files to run an SSH server to whatever the original firmware ships. Since nothing has been removed or modified otherwise, the chances of the device bricking are near zero.

If you do however softbrick the device somehow, you can hold shift while powering on the Prime 4 with the power button and it should throw you into update mode immediately. From there, you can run any official firmware update tool as available directly from Denon. This would also be the way to revert to official firmware in general.

The OpenSSH server as I compiled it is as standard as it gets, that includes the SFTP server it ships with. So you should be able to move files to your SSD once engine is up and running through SSH/SFTP.

**Comment by dzelionis** [comment]
@iikkart , chances are the same as if you were doing the official firmware update. It's always a small risk, in case you get some power outage while you flashing it....it could happen...but even if its gets bricked, there are good chances that you can recover it...as the motherboard is using the same approach as any of android phones (fastboot), and its kinda embedded into motherboard. Worst case scenario you will need to open it up, and press a button on the motherboard to put the device into the fastboot mode....then you can flash it again....
